# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: exp_grpc.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'exp_grpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65xp_grpc.proto\"\x1c\n\x08Mensagem\x12\x10\n\x08mensagem\x18\x01 \x01(\t\"1\n\x0b\x43onfirmacao\x12\x0f\n\x07tamanho\x18\x01 \x01(\x05\x12\x11\n\ttimestamp\x18\x02 \x01(\t23\n\x0e\x45nvioMensagens\x12!\n\x06\x65nviar\x12\t.Mensagem\x1a\x0c.Confirmacaob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'exp_grpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MENSAGEM']._serialized_start=18
  _globals['_MENSAGEM']._serialized_end=46
  _globals['_CONFIRMACAO']._serialized_start=48
  _globals['_CONFIRMACAO']._serialized_end=97
  _globals['_ENVIOMENSAGENS']._serialized_start=99
  _globals['_ENVIOMENSAGENS']._serialized_end=150
# @@protoc_insertion_point(module_scope)
