# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import trab1_pb2 as trab1__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in trab1_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ForumServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.inscrever = channel.unary_unary(
                '/ForumService/inscrever',
                request_serializer=trab1__pb2.SolicitacaoInscricao.SerializeToString,
                response_deserializer=trab1__pb2.Forum.FromString,
                _registered_method=True)
        self.publicar = channel.unary_unary(
                '/ForumService/publicar',
                request_serializer=trab1__pb2.SolicitacaoPublicacao.SerializeToString,
                response_deserializer=trab1__pb2.Publicacao.FromString,
                _registered_method=True)


class ForumServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def inscrever(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def publicar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ForumServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'inscrever': grpc.unary_unary_rpc_method_handler(
                    servicer.inscrever,
                    request_deserializer=trab1__pb2.SolicitacaoInscricao.FromString,
                    response_serializer=trab1__pb2.Forum.SerializeToString,
            ),
            'publicar': grpc.unary_unary_rpc_method_handler(
                    servicer.publicar,
                    request_deserializer=trab1__pb2.SolicitacaoPublicacao.FromString,
                    response_serializer=trab1__pb2.Publicacao.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ForumService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ForumService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ForumService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def inscrever(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ForumService/inscrever',
            trab1__pb2.SolicitacaoInscricao.SerializeToString,
            trab1__pb2.Forum.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def publicar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ForumService/publicar',
            trab1__pb2.SolicitacaoPublicacao.SerializeToString,
            trab1__pb2.Publicacao.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class UsuarioForumServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.receber = channel.unary_unary(
                '/UsuarioForumService/receber',
                request_serializer=trab1__pb2.Publicacao.SerializeToString,
                response_deserializer=trab1__pb2.Confirmacao.FromString,
                _registered_method=True)


class UsuarioForumServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def receber(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UsuarioForumServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'receber': grpc.unary_unary_rpc_method_handler(
                    servicer.receber,
                    request_deserializer=trab1__pb2.Publicacao.FromString,
                    response_serializer=trab1__pb2.Confirmacao.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'UsuarioForumService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('UsuarioForumService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UsuarioForumService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def receber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/UsuarioForumService/receber',
            trab1__pb2.Publicacao.SerializeToString,
            trab1__pb2.Confirmacao.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
