syntax = "proto3";

message Confirmacao {
    bool sucesso = 1;
}

message Usuario {
    uint64 id = 1;
    string nome = 2;
}

message SolicitacaoInscricao {
    uint64 id_forum = 1;
    Usuario usuario = 2;
}

message SolicitacaoPublicacao {
    uint64 id_forum = 1;
    uint64 id_usuario = 2;
    string mensagem = 3;
}

message Publicacao {
    uint64 id_mensagem = 1;
    uint64 id_forum = 2;
    uint64 id_usuario = 3;
    string timestamp = 4;
    string mensagem = 5;
}

service ForumService {

    // O cliente se inscreve em um fórum e recebe,
    // pelo mesmo fluxo, as novas publicações daquele fórum.
    rpc inscrever(SolicitacaoInscricao) returns (stream Publicacao);

    // O cliente publica uma mensagem em um fórum.
    rpc publicar(SolicitacaoPublicacao) returns (Confirmacao);
}